image: java:8

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
    - apt-get update -yq
    - apt-get install sbt -y
    - sbt test

deploy-production:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=commorg-staging --api-key=1e8d6840-65a8-4f85-9627-e7b2760894d6
  only:
    - master

deploy-staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=commorg-production --api-key=1e8d6840-65a8-4f85-9627-e7b2760894d6
  only:
    - development