variables:
  HEROKU_API_KEY: "1e8d6840-65a8-4f85-9627-e7b2760894d6"

deploy-production:
  script:
    - gem install dpl
    - dpl --provider=heroku --app=commorg-staging --api-key=HEROKU_API_KEY
  only:
    - master

deploy-staging:
  script:
    - gem install dpl
    - dpl --provider=heroku --app=commorg-production --api-key=HEROKU_API_KEY